version = 0.1
[default.deploy.parameters]
stack_name = "chatbot-cognito"
resolve_s3 = true
s3_prefix = "chatbot-cognito"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[dev.deploy.parameters]
stack_name = "chatbot-openai"
resolve_s3 = true
s3_prefix = "chatbot-openai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
